name: run_observer
description: A Flutter package to track app runs metrics with usefull callbacks
version: 0.1.0
homepage: https://github.com/inulugbek/run_observer
issue_tracker: https://github.com/inulugbek/run_observer/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0
